<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Refit" Version="8.0.0" />
    <PackageReference Include="Refit.HttpClientFactory" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http.Polly" Version="9.0.0" />
    <PackageReference Include="Polly.Contrib.WaitAndRetry" Version="1.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PhotoSiTest.Contracts\PhotoSiTest.Contracts.csproj" />
    <ProjectReference Include="..\PhotoSiTest.Common\PhotoSiTest.Common.csproj" />
  </ItemGroup>

</Project>
